<a href="https://colab.research.google.com/github/VictoriaIleanaRodriguezMora/uba_cbc_ingenieria/blob/dev/C%3A%5CUsers%5CVIV%5CDesktop%5CVICKY%5CVICKY_TAREAS%5CUBA%5Cuba_cbc_ingenieria%5Cpensamiento_computacional%5Csesion_10%5CEjercicios_sesion_10_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
peliculas = {'nombre': ['Titanic', 'Kil Bill', 'Matrix', 'El padrino', 'Avatar',
                        'Casablanca', 'El exorcista',  'Soy leyenda',
                        'El club de la pelea', 'Mujercitas'],
            'director': ['James Cameron', 'Quentin Tarantino', 'Hermanas Wachowski',
                        'Francis Ford Coppola', 'James Cameron', 'Michael Curtiz',
                        'William Friedkin', 'Francis Lawrence','David Fincher',
                        'Greta Gerwig'],
            'año': [1997, 2003, 1999, 1972, 2009, 1942, 1973, 2007, 1999, 2019],
            'género': ['romance', 'acción', 'ciencia ficción', 'drama', 'ciencia ficción', 'drama', 'terror',
                        'ciencia ficción', 'drama', 'drama'],
            'puntaje': [8.6, None, 6.9, 7.5, 9.1, 6.0, None, None, 9.4, 8.0]}

df = pd.DataFrame(peliculas)
df

                nombre              director   año           género  puntaje
0              Titanic         James Cameron  1997          romance      8.6
1             Kil Bill     Quentin Tarantino  2003           acción      NaN
2               Matrix    Hermanas Wachowski  1999  ciencia ficción      6.9
3           El padrino  Francis Ford Coppola  1972            drama      7.5
4               Avatar         James Cameron  2009  ciencia ficción      9.1
5           Casablanca        Michael Curtiz  1942            drama      6.0
6         El exorcista      William Friedkin  1973           terror      NaN
7          Soy leyenda      Francis Lawrence  2007  ciencia ficción      NaN
8  El club de la pelea         David Fincher  1999            drama      9.4
9           Mujercitas          Greta Gerwig  2019            drama      8.0

In [ ]:
df.iloc[3:]

                nombre              director   año           género  puntaje
3           El padrino  Francis Ford Coppola  1972            drama      7.5
4               Avatar         James Cameron  2009  ciencia ficción      9.1
5           Casablanca        Michael Curtiz  1942            drama      6.0
6         El exorcista      William Friedkin  1973           terror      NaN
7          Soy leyenda      Francis Lawrence  2007  ciencia ficción      NaN
8  El club de la pelea         David Fincher  1999            drama      9.4
9           Mujercitas          Greta Gerwig  2019            drama      8.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   nombre    10 non-null     object
 1   director  10 non-null     object
 2   año       10 non-null     int64
 3   género    10 non-null     object
 4   puntaje   7 non-null      float64
dtypes: float64(1), int64(1), object(3)
memory usage: 528.0+ bytes

In [ ]:
df.describe()

               año   puntaje
count    10.000000  7.000000
mean   1992.000000  7.928571
std      22.968578  1.221630
min    1942.000000  6.000000
25%    1979.000000  7.200000
50%    1999.000000  8.000000
75%    2006.000000  8.850000
max    2019.000000  9.400000

In [ ]:
# Mostrar la información del DataFrame con el método info(), ¿Cómo se llaman y qué tipo de dato tiene cada columna? ¿Cuántos elementos nulos hay en cada columna? Interpretar qué información se guarda en esta tabla y para qué puede servir.

In [ ]:
# Mostrar sólo los nombres de las primeras 3 películas del DataFrame.

In [ ]:
# Mostrar sólo el director y el género de todas las películas.

In [ ]:
 # Mostrar las películas que sean de drama

In [ ]:
# ¿Qué cantidad de películas hay de cada género?

In [ ]:
# Mostrar las películas que tengan puntaje entre 6 y 8 y cuyo año de estreno sea anterior a los 2000

In [ ]:
# Mostrar las películas que no hayan sido puntuadas (que el puntaje tenga un valor nulo).

In [ ]:
# Calcular el promedio del puntaje de todas las películas.

In [ ]:
# Ordenar las películas en orden alfabético descendente.

In [ ]:
# Mostrar las 3 películas más antiguas.

In [ ]:
# Mostrar sólo el nombre y el año de las 3 películas más nuevas.

In [ ]:
# Agregar una columna que indique si la película fue vista, o no. Una película fue vista cuando tiene puntaje no nulo